#ifndef __mainframe__
#define __mainframe__

/**
@file
Subclass of MainFrameBase, which is generated by wxFormBuilder.
*/

#include "guibase.h"

/** Implementing MainFrameBase */
class MainFrame : public MainFrameBase
{
protected:
	// Handlers for MainFrameBase events.
	void OnOpenFile( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnClose( wxCommandEvent& event );
	void OnSettings( wxCommandEvent& event );
	void OnLeftDown( wxMouseEvent& event );
	void OnLeftUp( wxMouseEvent& event );
	void OnMotion( wxMouseEvent& event );

	virtual void OnSaveAndNext( wxCommandEvent& event );
	virtual void OnSkipAndNext( wxCommandEvent& event );
	virtual void OnPrevious( wxCommandEvent& event );
	virtual void OnRows( wxSpinEvent& event );
	virtual void OnColumns( wxSpinEvent& event );
	virtual void OnFileType( wxCommandEvent& event );

public:
	/** Constructor */
	MainFrame( wxWindow* parent );
	void SetIsLastImage(bool li);
	void SetIsFirstImage(bool fi);

	enum GRIDDRAG
	{
		DRAG_NONE,
		DRAG_TOPLEFT,
		DRAG_TOPRIGHT,
		DRAG_BOTTOMRIGHT,
		DRAG_BOTTOMLEFT
	};


	GRIDDRAG SelectClosest(Grid const &g, double x, double y);

	GRIDDRAG m_dragGrid;
};

#endif // __mainframe__
